version: "3.7"

services:

  python:
    build: ./python
    container_name: python
    restart: always
    expose:
      - 8080


  nginx:
    build: ./nginx
    container_name: ngnix
    restart: always
    ports:
      - "80:80"







